/**************************************************
                Name        : PDepositionTurnInCtrl
                Author      : Lalit karamchandani
                Purpose     : Deposition details                
                Created Date: 04 FEB 2019
                
                
*****************************************************/
global class PDepositionTurnInCtrl {
    //@obsolete
    public PDepositionTurnInCtrl(ApexPages.StandardController controller) {
    }
}